spring.application.name=pg-activities-handler
server.port=8081

# MongoDB
# spring.data.mongodb.uri=mongodb://localhost:27017/pg_activities_db
spring.data.mongodb.uri=mongodb+srv://devands87_db_user:b0TpRSs0CzxD1Whq@cluster0.om3iihy.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=pg_activities_db

# JWT
app.jwt.secret=PGActivitiesHandlerSecretKey2024VeryLongSecretKeyForJWTSigningPurposes
app.jwt.expiration=86400000

# Logging
logging.level.com.pg=DEBUG
logging.level.org.springframework.security=WARN

# CORS - allow frontend
spring.web.cors.allowed-origins=https://pg-app-v1.netlify.app
